Logs = {
    Webhook       = "https://discord.com/api/webhooks/1351960985614680126/1Gg7TE3PLJjorO3pBP06GdX-CcAH_K_QRoPfsHkYUrv3lHSJZ1k9E-Jn1pUVIoV2MoUB", -- add webhook for all other Police logs URL here
    StorageWebook = "https://discord.com/api/webhooks/1351960985614680126/1Gg7TE3PLJjorO3pBP06GdX-CcAH_K_QRoPfsHkYUrv3lHSJZ1k9E-Jn1pUVIoV2MoUB", -- add Storage webhook URL here
    DutyWebhook   = "https://discord.com/api/webhooks/1351960985614680126/1Gg7TE3PLJjorO3pBP06GdX-CcAH_K_QRoPfsHkYUrv3lHSJZ1k9E-Jn1pUVIoV2MoUB", -- add Duty webhook URL here
    JailWebhook   = "https://discord.com/api/webhooks/1351960985614680126/1Gg7TE3PLJjorO3pBP06GdX-CcAH_K_QRoPfsHkYUrv3lHSJZ1k9E-Jn1pUVIoV2MoUB", -- add Jail webhook URL here
    Namelogs      = "Le Shériff",
    color         = 16711680, -- color for webhook embeds, defaults to VORP core config if not set
    logo          = "",       -- logo URL for webhook embeds, defaults to VORP core config
    footerLogo    = "",       -- footer logo URL for webhook embeds, defaults to VORP core config
    Avatar        = "",       -- avatar URL for webhook embeds, defaults to VORP core config
    Lang = {
        Steam           = "Steam : ",
        Identifier      = "Identifiant : ",
        PlayerID        = "ID Joueur : ",
        Job             = "Métier",
        PlayerName      = "Nom du Joueur : ",
        Jobfired        = "Officier Renvoyé : ",
        JobHired        = "Officier Embauché : ",
        JobOnDuty       = "Officier en Service : ",
        JobOffDuty      = "Officier Hors Service : ",
        FiredPlayer     = "Joueur Renvoyé : ",
        HiredPlayer     = "Joueur Embauché : ",
        FiredBy         = "Renvoyé par : ",
        HiredBy         = "Embauché par : ",
        JailledEvent    = "Emprisonné : ",
        UnjailEvent     = "Libéré de prison : ",
        Adjusted        = "Durée de peine ajustée",
        FromJob         = "Depuis le Métier : ",
        JailedPlayer    = "Joueur Emprisonné : ",
        JailedBy        = "Emprisonné par : ",
        JailTime        = "Durée de Peine (minutes) : ",
        UnjailedPlayer  = "Joueur Libéré : ",
        JailTimeChange  = "Changement de Durée (minutes) : ",
        NewTimeLeft     = "Temps Restant (minutes) : ",
        JailCompleted   = "Peine de Prison Terminée : ",
        ReleasedPlayer  = "Joueur Relâché : ",
        ReleasedByTime  = "Relâché Automatiquement après Peine Purge",
    }
}
